services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow:
    build: .
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=false
      - PYTHONPATH=/opt/airflow/src:/opt/airflow/dags
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./storage:/opt/airflow/storage
      - ./src:/opt/airflow/src
      - ./config:/opt/airflow/config
      - ./notebooks:/opt/airflow/notebooks
      - ./tests:/opt/airflow/tests
      - ./scripts:/opt/airflow/scripts 
    depends_on:
      - postgres
    command: >
      bash -c "
        # Wait for PostgreSQL to be ready
        until pg_isready -h postgres -p 5432; do echo 'Waiting for database...'; sleep 5; done;
        
        # Initialize database
        airflow db migrate || airflow db init;
        
        # Create admin user (if doesn't exist)
        airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com || true;
        
        # Start both webserver and scheduler
        airflow webserver &
        airflow scheduler
      "

volumes:
  postgres_data: